version: '3.8'
services:
  redis:
    image: "redis:latest"
    container_name: "redis-server"
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  server:
    image: "server"
    container_name: "aspnet-post"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080" 
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  mediaserver:
    image: "media-server"
    container_name: "aspnet-media"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  messagesserver:
    image: "messages-server"
    container_name: "aspnet-messages"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
    ports:
      - "8084:8084"
      - "8085:8085"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  authserver:
    image: "auth-server"
    container_name: "aspnet-auth"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8086
      - ASPNETCORE_HTTPS_PORTS=8087
    ports:
      - "8086:8086"
      - "8087:8087"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  userserver:
    image: "user-server"
    container_name: "aspnet-user"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8088
      - ASPNETCORE_HTTPS_PORTS=8089
    ports:
      - "8088:8088"
      - "8089:8089"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  adminserver:
    image: "admin-server"
    container_name: "aspnet-admin"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8091
      - ASPNETCORE_HTTPS_PORTS=8092
    ports:
      - "8091:8091"
      - "8092:8092"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"

  # angular:
  #   build:
  #     context: ../../Client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ../../Client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   stdin_open: true
  #   tty: true
