services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile

  mediaserver:
    image: ${DOCKER_REGISTRY-}mediaserver
    build:
      context: .
      dockerfile: MediaServer/Dockerfile

