version: '3.8'
services:
  springboot-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-server
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
